name: Deploy TTS App

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repo
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2

      # Step 2: Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::164229328614:role/GitHubTerraformRole
          aws-region: us-east-1

      # Step 3: Run backend deploy script (Lambda)
      - name: Deploy Lambda
        run: |
          chmod +x scripts/package_lambda.sh
          ./scripts/package_lambda.sh

      # Step 4: Run frontend deploy script (React → S3)
      - name: Deploy Frontend
        run: |
          chmod +x scripts/deploy_frontend.sh
          ./scripts/deploy_frontend.sh
